### ISSUE TITLE
Identity matrix cut is not correct

### ISSUE THREAD

**Issue by ariasanovsky** [ariasanovsky/signtensors#6]
If $s, t$ are optimal with respect to the identity matrix, then $s = \text{sgn}(I\cdot t) = t$.
Moreover, $c = 1/n$.

C.f. `cargo test first_sct_of_identity_has_s_equal_t` which has output

```shell
running 1 test
test sct::tests::first_sct_of_identity_has_s_equal_t ... FAILED

failures:

---- sct::tests::first_sct_of_identity_has_s_equal_t stdout ----
[src/sct.rs:493:9] &one_cut.sct = Sct {
    s: [
        0,
    ],
    c: [
        0.0,
    ],
    t: [
        13486662071293341567,
    ],
    nrows: 3,
    ncols: 3,
}
[
[0.0, 0.0, 0.0],
[0.0, 0.0, 0.0],
[0.0, 0.0, 0.0],
]
thread 'sct::tests::first_sct_of_identity_has_s_equal_t' panicked at src/sct.rs:495:9:
Assertion failed at src/sct.rs:495:9
Assertion failed: one_cut.sct.s [0] == one_cut.sct.t [0]
- one_cut.sct.s [0] = 0
- one_cut.sct.t [0] = 13486662071293341567
Assertion failed: (one_cut.sct.c [0] - (3 as f32).recip()).abs() < 1e-5
- (one_cut.sct.c [0] - (3 as f32).recip()).abs() = 0.33333334
- 1e-5 = 1e-5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    sct::tests::first_sct_of_identity_has_s_equal_t

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 8 filtered out; finished in 0.00s
```

**Comment by sarah-quinones** [comment]
fixed by 9340288
